import type { Metadata } from 'next';
import './globals.css';
import { volkhov, poppins } from './fonts';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${volkhov.variable} ${poppins.variable}  flex flex-col min-h-screen antialiased`}
      >
        <Header />
        <div className='flex-1 container'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
